# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Docs and Reference
email: support@helloroo.zendesk.com
description: Summary and implementation guidelines for Roo, a financial coaching chatbot platform
url: "" # If you are hosting online - the base hostname & protocol for your site
baseurl: "/" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
kramdown:
  auto_ids: true

include: ['_pages']
exclude: ['Gemfile', 'Gemfile.lock']

navigation:
- title: Overview
  url: /
- title: Diagrams and Flows
  url: /diagrams_and_flows/
- title: Using Roo
  url: /using-roo/
- title: Phase One
  url: /roadmap/phase-one
- title: Phase Two
  url: /roadmap/phase-two